/** Transactional renderer-only correction for an already committed Executive Brief. */
var EXECUTIVE_BRIEF_PDF_CORRECTION_CONFIRMATION = 'REPLACE EXECUTIVE BRIEF PDF';
var EXECUTIVE_BRIEF_PDF_CORRECTION_VERSION = 'WHEREWELOOKEDROWS-V1';

function replaceCurrentExecutiveBriefPdf() {
  const ui = SpreadsheetApp.getUi();
  const confirmation = ui.prompt(
    'Replace Current Executive Brief PDF',
    'Type ' + EXECUTIVE_BRIEF_PDF_CORRECTION_CONFIRMATION + ' exactly. This replaces only the verified canonical PDF and preserves its original generation history.',
    ui.ButtonSet.OK_CANCEL
  );
  if (confirmation.getSelectedButton() !== ui.Button.OK || confirmation.getResponseText() !== EXECUTIVE_BRIEF_PDF_CORRECTION_CONFIRMATION) {
    throw new Error('Executive Brief PDF replacement cancelled.');
  }
  const context = getSelectedProspectContext_(['Company', 'Prospect ID']);
  if (!context) return;
  const result = replaceCurrentExecutiveBriefPdfTransactional_(context, buildSelectedProspectForAuditPackage_(context), {});
  ui.alert(
    'Executive Brief PDF Replacement',
    result.status === 'already-completed' ? 'The corrected canonical PDF was already verified.' : 'The corrected canonical PDF replaced the prior file safely.',
    ui.ButtonSet.OK
  );
  return result;
}

function buildExecutiveBriefPdfCorrectionKey_(prospect, reference) {
  const approved = assertApprovedFindingSetReference_(reference);
  const prospectId = String(prospect && prospect.prospectId || '').trim();
  if (!prospectId) throw new Error('The selected prospect requires an exact Prospect ID.');
  return ['GOLDDOCCORRECTION', prospectId, 'EXECUTIVEBRIEF', approved.findingSetId, approved.version, approved.fingerprint, EXECUTIVE_BRIEF_PDF_CORRECTION_VERSION].join(':');
}

function executiveBriefCorrectionDescription_(correctionKey, artifactHash, originalOperationKey, originalGeneratedAt) {
  return 'Generated by Business Optimization Platform. Operation ' + correctionKey + '. Artifact SHA-256 ' + artifactHash + '. Original generation operation ' + originalOperationKey + '. Original generation at ' + originalGeneratedAt + '.';
}

function assertExecutiveBriefCorrectionAuthority_(context, prospect, plan, folder) {
  const originalOperationKey = buildGoldStandardGenerationOperationKey_(prospect, plan);
  const activity = findGoldStandardGenerationActivity_(context.ss, originalOperationKey);
  if (activity.rows.length !== 1) throw new Error('The original Executive Brief generation Activity is missing or ambiguous.');
  const activityValues = activity.sheet.getRange(activity.rows[0], 1, 1, activity.table.lastColumn).getValues()[0];
  const activityType = String(getValueByHeader_(activityValues, activity.table.headers, 'Activity Type') || '');
  const activityProspectId = String(getValueByHeader_(activityValues, activity.table.headers, 'Prospect ID') || '');
  const originalGeneratedAt = findingQualityDateText_(getValueByHeader_(activityValues, activity.table.headers, 'Date'));
  if (activityType !== GOLD_STANDARD_GENERATION_ACTIVITY_TYPES.executiveBrief || activityProspectId !== String(prospect.prospectId) || !originalGeneratedAt) {
    throw new Error('The original Executive Brief generation Activity is invalid.');
  }
  const canonicals = findAllAuditPackageFilesByName_(folder, plan.fileName);
  if (canonicals.length !== 1) throw new Error('The canonical Executive Brief PDF is missing or ambiguous.');
  const canonical = canonicals[0];
  const correctionKey = buildExecutiveBriefPdfCorrectionKey_(prospect, plan.approvedFindingSetReference);
  const description = String(canonical.getDescription() || '');
  const isOriginal = description.indexOf('Operation ' + originalOperationKey + '.') !== -1;
  const isCorrected = description.indexOf('Operation ' + correctionKey + '.') !== -1;
  if (!isOriginal && !isCorrected) throw new Error('The canonical Executive Brief PDF does not match its approved generation authority.');
  const currentHash = hashGoldStandardBlob_(canonical.getBlob());
  if (description.indexOf('Artifact SHA-256 ' + currentHash + '.') === -1) throw new Error('The canonical Executive Brief PDF hash is invalid.');
  return {
    originalOperationKey: originalOperationKey,
    originalGeneratedAt: originalGeneratedAt,
    correctionKey: correctionKey,
    canonicalFileId: canonical.getId(),
    corrected: isCorrected
  };
}

function assertExecutiveBriefCheckedRows_(plan) {
  const references = [].concat(plan && plan.content && plan.content.evidenceReferences || []);
  if (!references.length) throw new Error('The Executive Brief requires at least one approved evidence reference.');
  const html = String(plan && plan.pdfHtml || '');
  const whereStart = html.toLowerCase().indexOf('where we looked');
  const whereEnd = html.toLowerCase().indexOf('what we did not test', whereStart);
  const block = whereStart >= 0 && whereEnd > whereStart ? html.slice(whereStart, whereEnd) : '';
  const badges = (block.match(/&#10003; Checked/g) || []).length;
  if (badges !== references.length) throw new Error('Executive Brief preview/PDF evidence-row parity is invalid.');
  references.forEach(function(reference) {
    if (block.indexOf(escapeHtml_(reference)) === -1) throw new Error('Executive Brief PDF is missing an approved evidence reference.');
  });
  return true;
}

function assertExecutiveBriefCorrectionReadback_(context, prospect, plan, folder, authority, artifact, prospectBefore) {
  const canonicals = findAllAuditPackageFilesByName_(folder, plan.fileName);
  if (canonicals.length !== 1 || canonicals[0].getId() !== artifact.file.getId()) throw new Error('Corrected Executive Brief canonical readback is invalid.');
  verifyGoldStandardDriveFile_(canonicals[0], plan.fileName, artifact.artifactHash);
  const expectedDescription = executiveBriefCorrectionDescription_(authority.correctionKey, artifact.artifactHash, authority.originalOperationKey, authority.originalGeneratedAt);
  if (String(canonicals[0].getDescription() || '') !== expectedDescription) throw new Error('Corrected Executive Brief audit description is invalid.');
  if (findGoldStandardGenerationActivity_(context.ss, authority.originalOperationKey).rows.length !== 1) throw new Error('Original generation Activity changed during PDF correction.');
  const prospectAfter = context.sheet.getRange(context.selectedRow, 1, 1, context.table.lastColumn).getValues()[0];
  if (stableStringifyFindingQuality_(prospectAfter) !== stableStringifyFindingQuality_(prospectBefore)) throw new Error('Prospect state changed during PDF correction.');
  return true;
}

function replaceCurrentExecutiveBriefPdfTransactional_(context, prospect, hooks) {
  const lock = LockService.getDocumentLock();
  lock.waitLock(30000);
  try {
    const approved = loadApprovedFindingSetForGeneration_(prospect, {});
    const plan = buildGoldStandardDocumentPlan_('executiveBrief', prospect, {}, { approvedFindingSetReference: approved.reference });
    assertExecutiveBriefCheckedRows_(plan);
    const folder = getExistingClientArtifactFolder_(prospect.company);
    if (!folder) throw new Error('The existing client Drive folder is required for Executive Brief correction.');
    const authority = assertExecutiveBriefCorrectionAuthority_(context, prospect, plan, folder);
    const prospectBefore = context.sheet.getRange(context.selectedRow, 1, 1, context.table.lastColumn).getValues()[0];
    let artifact = null;
    try {
      artifact = stageAndCommitGoldStandardArtifact_(folder, plan, authority.correctionKey);
      if (hooks && hooks.afterArtifact) hooks.afterArtifact(artifact);
      artifact.file.setDescription(executiveBriefCorrectionDescription_(authority.correctionKey, artifact.artifactHash, authority.originalOperationKey, authority.originalGeneratedAt));
      if (hooks && hooks.afterDescription) hooks.afterDescription(artifact);
      assertExecutiveBriefCorrectionReadback_(context, prospect, plan, folder, authority, artifact, prospectBefore);
      return {
        status: artifact.artifactChanged ? 'completed' : 'already-completed',
        operationKey: authority.correctionKey,
        fileId: String(artifact.file.getId()),
        artifactHash: String(artifact.artifactHash),
        originalOperationKey: authority.originalOperationKey,
        originalGeneratedAt: authority.originalGeneratedAt
      };
    } catch (error) {
      if (artifact && artifact.artifactChanged) rollbackGoldStandardArtifactCommit_(folder, plan, artifact, authority.correctionKey);
      throw error;
    }
  } finally {
    lock.releaseLock();
  }
}
