const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const crypto = require('node:crypto');

const ROOT = path.resolve(__dirname, '..');
const SOURCE = fs.readFileSync(path.join(ROOT, 'ClientPackageDraftEngine.gs'), 'utf8');
const MENU = fs.readFileSync(path.join(ROOT, 'Menu.gs'), 'utf8');
const HASH = '70a20a6d7ef2427430699251188a8358a31bbcfda8b02f2e15a1431f9a7c0629';

function iterator(items) {
  let index = 0;
  return { hasNext: () => index < items.length, next: () => items[index++] };
}

function sha(bytes) { return crypto.createHash('sha256').update(Buffer.from(bytes)).digest('hex'); }

function load(extra = {}) {
  const context = {
    console,
    MimeType: { PDF: 'application/pdf' },
    Utilities: {
      Charset: { UTF_8: 'UTF_8' },
      DigestAlgorithm: { SHA_256: 'SHA_256' },
      computeDigest(_algorithm, value) {
        const bytes = Array.isArray(value) ? Buffer.from(value) : Buffer.from(String(value));
        return [...crypto.createHash('sha256').update(bytes).digest()].map(n => n > 127 ? n - 256 : n);
      }
    },
    escapeHtml_: value => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'),
    normalizeGmailDraftRecipient_: value => String(value || '').trim().toLowerCase(),
    assertUnambiguousGmailDraftMatches_: matches => { if (matches.length > 1) throw new Error('Multiple Gmail drafts'); },
    assertApprovedFindingSetReference_: value => value,
    hashGoldStandardBlob_: blob => sha(blob.getBytes()),
    findingQualityDateText_: value => value instanceof Date ? value.toISOString() : String(value || ''),
    buildExecutiveBriefPdfCorrectionKey_: (prospect, reference) => `GOLDDOCCORRECTION:${prospect.prospectId}:EXECUTIVEBRIEF:${reference.findingSetId}:${reference.version}:${reference.fingerprint}:WHEREWELOOKEDROWS-V1`,
    executiveBriefCorrectionDescription_: (key, hash, original, at) => `Generated by Business Optimization Platform. Operation ${key}. Artifact SHA-256 ${hash}. Original generation operation ${original}. Original generation at ${at}.`,
    setIfHeader_: (row, headers, header, value) => { if (headers[header]) row[headers[header] - 1] = value; },
    getValueByHeader_: (row, headers, header) => headers[header] ? row[headers[header] - 1] : '',
    literalizeBusinessSnapshotSheetRow_: row => row,
    stableStringifyFindingQuality_: JSON.stringify,
    ACTIVITY_FEED_SHEET: 'Activity Feed',
    ...extra
  };
  vm.createContext(context);
  vm.runInContext(SOURCE, context);
  return context;
}

function fakeBlob(name, bytes) {
  return { name, bytes, getName() { return this.name; }, setName(value) { this.name = value; return this; }, getBytes() { return this.bytes; } };
}

function fakeFile(name, token, bytes, descriptionOverride) {
  const hash = sha(bytes);
  return {
    name, bytes, trashed: false,
    getName() { return this.name; }, isTrashed() { return this.trashed; },
    getMimeType() { return 'application/pdf'; }, getSize() { return this.bytes.length; },
    getBlob() { return fakeBlob(this.name, this.bytes.slice()); },
    getDescription() { return descriptionOverride || `Generated by Business Optimization Platform. Operation ${token}. Artifact SHA-256 ${hash}.`; }
  };
}

function harness(options = {}) {
  const prospectId = 'PROS-AF21065CD5C8';
  const ref = { findingSetId: 'FSET-a2ae86fa62d97824', version: '1', fingerprint: HASH };
  const names = ['Executive Brief.pdf', 'Digital Business Assessment.pdf', 'Improvement Plan.pdf'];
  const tokens = ['EXECUTIVEBRIEF', 'DIGITALBUSINESSASSESSMENT', 'IMPROVEMENTPLAN'];
  const originalKeys = tokens.map(token => `GOLDDOC:${prospectId}:${token}:${ref.findingSetId}:1:${HASH}`);
  const correctionKey = `GOLDDOCCORRECTION:${prospectId}:EXECUTIVEBRIEF:${ref.findingSetId}:1:${HASH}:WHEREWELOOKEDROWS-V1`;
  const briefBytes = [1, 2, 3];
  const correctedDescription = `Generated by Business Optimization Platform. Operation ${correctionKey}. Artifact SHA-256 ${sha(briefBytes)}. Original generation operation ${originalKeys[0]}. Original generation at 2026-08-19T01:00:00.000Z.`;
  const briefDescription = options.unknownCorrection
    ? correctedDescription.replace('WHEREWELOOKEDROWS-V1', 'UNKNOWN-V2')
    : options.missingCorrectionAuthority
      ? `Generated by Business Optimization Platform. Operation ${correctionKey}. Artifact SHA-256 ${sha(briefBytes)}.`
      : options.duplicateCorrectionAuthority
        ? correctedDescription + ` Operation ${correctionKey}.`
        : options.correctedBrief ? correctedDescription : null;
  const files = names.map((name, i) => fakeFile(name, originalKeys[i], i === 0 ? briefBytes : [i + 1, i + 2, i + 3], i === 0 ? briefDescription : null));
  if (options.alteredBriefBytes) files[0].bytes.push(99);
  if (options.missingPdf) files.pop();
  if (options.duplicatePdf) files.push(files[0]);
  if (options.extraPdf) files.push(fakeFile('backup.pdf', 'bad', [9]));
  const folder = { getFiles: () => iterator(files) };
  const headers = { 'Prospect ID': 1, 'Last Activity': 2, 'Next Action': 4, 'Gmail Draft Created': 6, Company: 8, Email: 10 };
  const row = new Array(10).fill('fixture-preserved');
  row[0] = prospectId; row[1] = 'ORIGINAL-TIME'; row[3] = 'Confirm Improvement Plan Sent'; row[5] = ''; row[7] = 'Rogers Holdings LLC'; row[9] = 'briankeith@rogersholdingsllc.com';
  const trackerSheet = {
    getRange(_r, _c, _nr, _nc) { return { getValues: () => [row.slice()], setValues: values => {
      if (options.failWorkbookWrite) throw new Error('workbook failure');
      row.splice(0, row.length, ...values[0]);
    } }; }
  };
  const activityHeaders = { Date: 1, Company: 2, 'Activity Type': 3, 'Activity Notes': 4, 'Prospect ID': 7, 'Operation Key': 8 };
  const activityRows = [new Array(8).fill('synthetic-fixture-preserved')];
  names.forEach((name, i) => {
    const receipt = new Array(8).fill('');
    receipt[0] = new Date('2026-08-19T0' + (i + 1) + ':00:00Z');
    receipt[1] = 'Rogers Holdings LLC';
    receipt[2] = name.replace('.pdf', '') + ' Generated';
    receipt[3] = `Generated ${name} from approved Finding Quality snapshot ${ref.findingSetId} v1.`;
    receipt[6] = prospectId;
    receipt[7] = `GOLDDOC:${prospectId}:${tokens[i]}:${ref.findingSetId}:1:${HASH}`;
    activityRows.push(receipt);
  });
  const activitySheet = {
    getLastRow: () => 4 + activityRows.length,
    getRange(r) { return {
      getValues: () => [activityRows[r - 5].slice()],
      setValues: values => {
        if (options.failActivityWrite) throw new Error('activity failure');
        activityRows[r - 5] = values[0].slice();
      }
    }; },
    deleteRow(r) { activityRows.splice(r - 5, 1); }
  };
  const drafts = [];
  function makeDraft(recipient, subject, plain, draftOptions) {
    const timestamp = new Date('2026-08-19T12:00:00Z');
    let attachmentBlobs = (draftOptions.attachments || []).map(blob => fakeBlob(blob.getName(), blob.getBytes().slice()));
    if (options.reverseGmailAttachments) attachmentBlobs = attachmentBlobs.reverse();
    const persistedPlain = options.gmailNormalizedBodies ? plain.replace(/\n/g, '\r\n') + '\r\n' : plain;
    const persistedHtml = options.gmailNormalizedBodies ? `<div dir="ltr">${draftOptions.htmlBody}</div>` : draftOptions.htmlBody;
    return {
      deleted: false,
      getId: () => 'DRAFT-1',
      deleteDraft() { this.deleted = true; const i = drafts.indexOf(this); if (i >= 0) drafts.splice(i, 1); },
      getMessage: () => ({
        getTo: () => recipient, getSubject: () => subject, getPlainBody: () => persistedPlain,
        getBody: () => persistedHtml, getAttachments: () => attachmentBlobs,
        getDate: () => timestamp
      })
    };
  }
  const context = load({
    LockService: { getDocumentLock: () => ({ waitLock() {}, releaseLock() {} }) },
    loadApprovedFindingSetForGeneration_: () => ({ reference: ref }),
    getAuditPackageFolder_: () => folder,
    getRequiredSheet_: () => activitySheet,
    getHeaderTable_: () => ({ headers: activityHeaders, lastColumn: 8, headerRow: 4 }),
    findRowsByExactHeaderValue_: (_sheet, _table, _header, value) => activityRows.map((r, i) => r[7] === value ? i + 5 : 0).filter(Boolean),
    restoreGoldStandardProspectRow_: (_context, before) => row.splice(0, row.length, ...before),
    findExactGmailDraftMatches_: (recipient, subject) => drafts.filter(d => {
      const m = d.getMessage(); return m.getTo().toLowerCase() === recipient.toLowerCase() && m.getSubject() === subject;
    }),
    GmailApp: { createDraft: (recipient, subject, plain, draftOptions) => {
      if (options.failGmailCreate) throw new Error('gmail failure');
      const draft = makeDraft(recipient, subject, plain, draftOptions); drafts.push(draft); return draft;
    } }
  });
  const selected = { ss: {}, sheet: trackerSheet, table: { headers, lastColumn: 10 }, selectedRow: 21, prospect: { prospectId, company: 'Rogers Holdings LLC', email: 'briankeith@rogersholdingsllc.com', contact: 'Brian Keith Rogers' } };
  return { context, selected, row, activityRows, drafts, files, ref };
}

test('valid pasted HTTPS Return Link trims only surrounding whitespace', () => {
  const c = load();
  assert.equal(c.validateClientPackageReturnLink_('  https://example.com/a%2Fb?x=One%20Two&y=%2F#Frag%2FKeep  '), 'https://example.com/a%2Fb?x=One%20Two&y=%2F#Frag%2FKeep');
});

test('live Rogers Return Links validate without a browser or Node URL global and preserve exact text', () => {
  const c = load();
  for (const value of [
    'https://rogersholdingsllc.com/',
    'https://rogersholdingsllc.com/#contact',
    'https://rogersholdingsllc.com/contact?source=package#reply'
  ]) assert.equal(c.validateClientPackageReturnLink_(value), value);
  assert.equal(c.validateClientPackageReturnLink_('  HTTPS://RogersHoldingsLLC.com/Contact?Source=Package%2FReply#Reply  '), 'HTTPS://RogersHoldingsLLC.com/Contact?Source=Package%2FReply#Reply');
});

test('blank, malformed, HTTP, credential-bearing, multiline, and unsupported URLs reject', () => {
  const c = load();
  for (const value of ['', 'not a url', '/relative', 'http://example.com', 'https://user:pass@example.com/x', 'https://example.com/a\nhttps://evil.example', 'https://example.com/a b', 'https://example.com/%ZZ', 'https://example.com\\evil', 'https://', 'https://bad_host.example/', 'https://example.com:99999/', 'ftp://example.com/x']) {
    assert.throws(() => c.validateClientPackageReturnLink_(value));
  }
});

test('prompt response reaches validation and the transaction without transformation or discarding', () => {
  const entered = '  https://rogersholdingsllc.com/contact?source=package#reply  ';
  const prompts = [
    { getSelectedButton: () => 'OK', getResponseText: () => entered },
    { getSelectedButton: () => 'OK', getResponseText: () => 'CREATE CLIENT PACKAGE DRAFT' }
  ];
  let validatedRaw = null;
  let transactionValue = null;
  const c = load({
    getSelectedProspectContext_: () => ({ prospect: {} }),
    SpreadsheetApp: { getUi: () => ({ ButtonSet: { OK_CANCEL: 'OK_CANCEL', OK: 'OK' }, Button: { OK: 'OK' }, prompt: () => prompts.shift(), alert() {} }) }
  });
  const actualValidator = c.validateClientPackageReturnLink_;
  c.validateClientPackageReturnLink_ = value => { validatedRaw = value; return actualValidator(value); };
  c.createClientPackageGmailDraftTransactional_ = (_context, value) => { transactionValue = value; return { status: 'completed', ok: true }; };
  c.serializeClientPackageDraftResult_ = () => '{}';
  c.createClientPackageGmailDraft();
  assert.equal(validatedRaw, entered);
  assert.equal(transactionValue, 'https://rogersholdingsllc.com/contact?source=package#reply');
});

test('missing, duplicate, extra, staged, backup, and ambiguous PDFs reject before mutation', () => {
  for (const key of ['missingPdf', 'duplicatePdf', 'extraPdf']) {
    const h = harness({ [key]: true });
    assert.throws(() => h.context.createClientPackageGmailDraftTransactional_(h.selected, 'https://example.com/return'));
    assert.equal(h.drafts.length, 0);
    assert.equal(h.row[1], 'ORIGINAL-TIME');
  }
});

test('uncorrected canonical Executive Brief is accepted against its exact original GOLDDOC receipt', () => {
  const h = harness();
  const loaded = h.context.loadVerifiedClientPackagePdfFiles_(h.selected, { prospect: h.selected.prospect, reference: h.ref });
  assert.equal(loaded.files[0].correctionOperationKey, '');
});

test('supported corrected Executive Brief is accepted through exact original and correction lineage', () => {
  const h = harness({ correctedBrief: true });
  const loaded = h.context.loadVerifiedClientPackagePdfFiles_(h.selected, { prospect: h.selected.prospect, reference: h.ref });
  assert.match(loaded.files[0].correctionOperationKey, /GOLDDOCCORRECTION:.*:WHEREWELOOKEDROWS-V1$/);
});

test('unknown, missing, or duplicate Executive Brief correction authority rejects', () => {
  for (const option of [{ unknownCorrection: true }, { missingCorrectionAuthority: true }, { duplicateCorrectionAuthority: true }]) {
    const h = harness(option);
    assert.throws(() => h.context.loadVerifiedClientPackagePdfFiles_(h.selected, { prospect: h.selected.prospect, reference: h.ref }));
  }
});

test('altered corrected Executive Brief bytes or stale hash rejects', () => {
  const h = harness({ correctedBrief: true, alteredBriefBytes: true });
  assert.throws(() => h.context.loadVerifiedClientPackagePdfFiles_(h.selected, { prospect: h.selected.prospect, reference: h.ref }), /correction authority|lineage/);
});

test('creates one verified draft with exactly three canonical attachments and one Activity', () => {
  const h = harness({ gmailNormalizedBodies: true, reverseGmailAttachments: true });
  const result = h.context.createClientPackageGmailDraftTransactional_(h.selected, 'https://example.com/return?x=1#go');
  assert.equal(result.status, 'completed');
  assert.equal(h.drafts.length, 1);
  assert.deepEqual(Array.from(result.attachmentNames), ['Executive Brief.pdf', 'Digital Business Assessment.pdf', 'Improvement Plan.pdf']);
  assert.equal(h.activityRows.length, 5);
  assert.equal(h.row[5], 'Yes');
  assert.equal(h.row[3], 'Confirm Improvement Plan Sent');
  assert.equal(h.row[2], 'fixture-preserved');
  assert.match(h.drafts[0].getMessage().getBody(), /<strong>Return Link:<\/strong> <a href="https:\/\/example\.com\/return\?x=1#go">/);
});

test('Gmail MIME normalization and attachment reordering do not cause a false readback failure', () => {
  const h = harness({ correctedBrief: true, gmailNormalizedBodies: true, reverseGmailAttachments: true });
  const result = h.context.createClientPackageGmailDraftTransactional_(h.selected, 'https://example.com/return#reply');
  assert.equal(result.status, 'completed');
  assert.equal(h.drafts.length, 1);
  assert.equal(h.activityRows.length, 5);
});

test('exact retry preserves Gmail and workbook timestamps and adds no Activity', () => {
  const h = harness({ correctedBrief: true });
  const first = h.context.createClientPackageGmailDraftTransactional_(h.selected, 'https://example.com/return');
  const draftTime = h.drafts[0].getMessage().getDate().getTime();
  const workbookTime = h.row[1].getTime();
  const count = h.activityRows.length;
  const second = h.context.createClientPackageGmailDraftTransactional_(h.selected, 'https://example.com/return');
  assert.equal(first.status, 'completed');
  assert.equal(second.status, 'already-completed');
  assert.equal(h.drafts[0].getMessage().getDate().getTime(), draftTime);
  assert.equal(h.row[1].getTime(), workbookTime);
  assert.equal(h.activityRows.length, count);
});

test('partial Gmail/workbook/Activity failure rolls back only operation-owned state', () => {
  for (const failure of [{ failGmailCreate: true }, { failWorkbookWrite: true }, { failActivityWrite: true }]) {
    const h = harness(failure);
    const before = h.row.slice();
    assert.throws(() => h.context.createClientPackageGmailDraftTransactional_(h.selected, 'https://example.com/return'));
    assert.deepEqual(h.row, before);
    assert.equal(h.drafts.length, 0);
    assert.equal(h.activityRows.length, 4);
    assert.ok(h.activityRows[0].every(value => value === 'synthetic-fixture-preserved'));
  }
});

test('transport response is a primitive JSON string containing primitives and primitive arrays', () => {
  const c = load();
  const response = c.serializeClientPackageDraftResult_({ ok: true, status: 'completed', operationKey: 'KEY', prospectId: 'P1', findingSetId: 'F1', findingSetVersion: '1', immutableHash: 'h', draftId: 'd', attachmentNames: ['a'], attachmentHashes: ['b'], activityTimestamp: 't' });
  assert.equal(typeof response, 'string');
  const parsed = JSON.parse(response);
  assert.equal(parsed.ok, true);
  assert.deepEqual(parsed.attachmentNames, ['a']);
});

test('hidden/reordered columns are addressed exclusively through header maps', () => {
  const h = harness();
  h.context.createClientPackageGmailDraftTransactional_(h.selected, 'https://example.com/return');
  assert.equal(h.row[0], 'PROS-AF21065CD5C8');
  assert.equal(h.row[5], 'Yes');
  assert.equal(h.row[7], 'Rogers Holdings LLC');
});

test('menu exposes the command and source excludes sends, generation, production, and unrelated side effects', () => {
  assert.match(MENU, /Create Complete Client Package Gmail Draft.*createClientPackageGmailDraft/);
  assert.doesNotMatch(SOURCE, /sendEmail|sendDraft|GmailApp\.send|generateExecutive|generateAuditPackage|generateProposal|createFile|Assessment Action|proposal|website change|1aoOL0_ff6PARRB53rh8YbvjNBfgV4EpWrqeyiiHKd0ZTbESxgMdumsKo/);
  assert.match(SOURCE, /GmailApp\.createDraft/);
  assert.doesNotMatch(SOURCE, /new URL\(/);
  assert.match(SOURCE, /CLIENT_PACKAGE_DRAFT_CONFIRMATION = 'CREATE CLIENT PACKAGE DRAFT'/);
});
