const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');
const ROOT = path.resolve(__dirname, '..');
const PROSPECT='PROS-AF21065CD5C8', FINDING='FND-24cd3f413759a988', REC='REC-f5bed865a14ef641', SET='FSET-a2ae86fa62d97824';
const approved={expectedCondition:'Visitors submit the Business Snapshot directly on the website and receive confirmation without opening or sending an email.',consequenceBasis:'The page states that its secure submission endpoint is not connected. The form instead prepares an email that the visitor must send. This added handoff prevents the website from recording a completed structured submission directly.',businessConsequence:'The extra step can cause abandoned or incomplete requests. It also makes lead tracking less dependable.',recommendedAction:'Connect the Business Snapshot form to a secure submission system so customers can submit directly from the website. Each valid submission should create the appropriate linked intake records and preserve explicit consent. Rogers Holdings should receive a notification, and the visitor should receive clear confirmation. No manually sent email should be required.',completionTest:'Submit an authorized test Business Snapshot through the published form. Verify that no email client is required. Confirm one complete linked intake record contains the submitted fields and consent. Confirm Rogers Holdings receives the configured notification. Confirm the visitor receives a clear confirmation. Verify invalid submissions create no incomplete records.'};

function harness(options={}) {
  const c=vm.createContext({Object,Array,Date,JSON,Math,Number,String,RegExp,Set,isFinite,console,SpreadsheetApp:{flush(){}},LockService:{getDocumentLock:()=>({waitLock(){},releaseLock(){}})}});
  vm.runInContext(fs.readFileSync(path.join(ROOT,'FindingQualityEngine.gs'),'utf8'),c);
  vm.runInContext(fs.readFileSync(path.join(ROOT,'PreSnapshotRecoveryEngine.gs'),'utf8'),c);
  const finding={'Finding ID':FINDING,'Prospect ID':PROSPECT,'Finding Set ID':SET,'Finding Set Version':'1',Category:'Contact Path / Lead Capture','Finding Title':'Business Snapshot intake adds an email handoff','Finding State':'Actionable','Channel Type':'Website','Presence State':'Verified Present','Customer Journey Stage':'Request a Business Snapshot','Business Objective':'Get more customers and build steady revenue as soon as possible.','Evidence Source':'Page Content, Page Content','Evidence Location':'https://rogersholdingsllc.com/business-snapshot/','Evidence Observed At':'2026-08-17','Evidence Excerpt':'The reviewed conversion destination returned a readable HTML page.',Observation:'The Business Snapshot form is not connected to a secure submission endpoint. It prepares an email for the visitor to review and send.','Expected Condition':'','Business Consequence':'The extra step can cause prospective customers to abandon or incompletely send requests and makes lead tracking less dependable.','Consequence Basis':'','Recommended Action':'','Implementation Location':'','Intended Outcome':'','Completion Test':'','Evidence Confidence':0.9,'Evidence References':'EVID-1, EVID-2',Limitations:'No submission was performed.','Recommendation ID':REC,'Reviewed By':'brian','Reviewed At':'2026-08-17','Approval Status':'Approved for Client','Approved Version':'1','Approval Operation Key':'FQFINDINGAPPROVAL:key'};
  const recommendation={'Recommendation ID':REC,'Prospect ID':PROSPECT,'Finding Set ID':SET,'Finding Set Version':'1','Finding ID':FINDING,Title:'Connect the Business Snapshot form to secure direct submission','Recommended Action':'Connect the Business Snapshot form to a secure submission system so customers can submit directly from the website.','Implementation Location':'Business Snapshot form submission workflow','Intended Outcome':'Create a simpler and more dependable lead-capture path with structured intake records and auditable follow-up.',Dependencies:'','Review Status':'Reviewed','Operation Key':'FQRECOMMENDATIONDRAFT:key',Limitations:'Do not promise increased revenue, conversion rates, lead volume, or guaranteed results. Implementation and end-to-end submission testing have not yet occurred.','Reviewed By':'brian','Reviewed At':'2026-08-17','Review Operation Key':'FQRECOMMENDATIONREVIEW:key'};
  const set={'Finding Set ID':SET,'Prospect ID':PROSPECT,Version:'1','Review Status':options.reviewedSet?'In Review':'Draft','Approval Status':'Not Reviewed','Document Eligibility':'Not Eligible','Business Context Version':'1','Presence Inventory Version':'1','Evidence References':'EVID-1, EVID-2','Finding IDs':FINDING,'Immutable Hash':options.snapshot?'hash':'','Snapshot File ID':options.snapshot?'file':''};
  const records={};
  function entry(name,columns,rows){const sheet={records:rows.map(x=>Object.assign({},x)),getLastRow(){return this.records.length+1;},getMaxRows(){return 200;},getMaxColumns(){return columns.length;},getColumnWidth(){return 100;},isColumnHiddenByUser(){return false;},deleteRow(row){this.records.splice(row-2,1);},getRange(row){return{getValues:()=>[columns.map(h=>(sheet.records[row-2]||{})[h]||'')],setValues:v=>{sheet.records[row-2]=Object.fromEntries(columns.map((h,i)=>[h,v[0][i]]));},getDataValidations:()=>[[{}]],setDataValidations(){}};}};records[name]={sheet,table:{headerRow:1,headers:Object.fromEntries(columns.map((h,i)=>[h,i+1])),lastColumn:columns.length},missingHeaders:[],requiredLastColumn:columns.length};}
  entry(c.FQ_FINDINGS_SHEET,c.FQ_FINDING_COLUMNS,[finding,{'Finding ID':'FND-SYNTH','Prospect ID':'FQ1-WEBGBP-001'}]);entry(c.FQ_RECOMMENDATIONS_SHEET,c.FQ_RECOMMENDATION_COLUMNS,[recommendation,{'Recommendation ID':'REC-SYNTH','Prospect ID':'FQ1-WEBGBP-001'}]);entry(c.FQ_FINDING_SETS_SHEET,c.FQ_FINDING_SET_COLUMNS,[set]);entry(c.FQ_ACTIONS_SHEET,c.FQ_ACTION_COLUMNS,options.action?[{'Action ID':'ACT-EXISTS','Prospect ID':PROSPECT}]:[]);entry(c.FQ_CONTEXT_SHEET,c.FQ_CONTEXT_COLUMNS,[{}]);entry(c.FQ_PRESENCE_SHEET,c.FQ_PRESENCE_COLUMNS,[{}]);entry(c.FQ_EVIDENCE_SHEET,c.FQ_EVIDENCE_COLUMNS,[{'Evidence ID':'EVID-1'},{'Evidence ID':'EVID-2'}]);
  c.getPreSnapshotRecoverySchema_=()=>records;c.readFindingQualityRecordsWithRows_=e=>e.sheet.records.map((r,i)=>Object.assign({},r,{_row:i+2}));c.readFindingQualityRecords_=(sheet)=>sheet.records.map(r=>Object.assign({},r));c.readFindingQualityRecord_=(sheet,_t,row)=>Object.assign({},sheet.records[row-2]);c.writeFindingQualityRecord_=(sheet,_t,row,r)=>{const x=Object.assign({},r);delete x._row;sheet.records[row-2]=x;};c.appendFindingQualityRecord_=(sheet,_t,r)=>{sheet.records.push(Object.assign({},r));return sheet.records.length+1;};c.resolveRecommendationDraftAuthority_=()=>({context:{},presence:{},evidence:[{'Evidence ID':'EVID-1'},{'Evidence ID':'EVID-2'}],set});c.buildRecommendationDraftOperationIdentity_=()=>({recommendationId:REC,operationKey:'FQRECOMMENDATIONDRAFT:key'});c.assertRecommendationSeedIdentity_=()=>({recommendationId:REC,operationKey:'FQRECOMMENDATIONDRAFT:key'});c.normalizeRecommendationDraftCandidate_=x=>x;c.validateStandaloneDraftRecommendation_=()=>{};c.validateAssessmentFindingRecord_=()=>[];c.migratePreSnapshotSchema_=()=>{};c.requireHumanReviewer_=()=> 'briankeith@rogersholdingsllc.com';c.buildPreSnapshotRecoveryIdentity_=()=>({operationKey:'FQPRESNAPSHOTRECOVERY:'+FINDING+':authority:candidate',findingId:'FND-CORRECTION-1',recommendationId:'REC-CORRECTION-1'});
  const selected={ss:{},record:Object.assign({},finding),row:2}; return {c,records,selected,finding,recommendation,set};
}

test('clean recovery preserves history, creates linked Draft successors, and replaces active membership',()=>{const h=harness();const oldFinding=JSON.stringify(h.finding),oldRec=JSON.stringify(h.recommendation),synthF=JSON.stringify(h.records[h.c.FQ_FINDINGS_SHEET].sheet.records[1]),synthR=JSON.stringify(h.records[h.c.FQ_RECOMMENDATIONS_SHEET].sheet.records[1]);const result=h.c.createPreSnapshotCorrectionDraftLocked_(h.selected,approved,{});assert.equal(result.status,'completed');const fsheet=h.records[h.c.FQ_FINDINGS_SHEET].sheet.records,rsheet=h.records[h.c.FQ_RECOMMENDATIONS_SHEET].sheet.records;assert.equal(fsheet[0]['Finding State'],'Superseded Pre-Snapshot');assert.equal(fsheet[0]['Approval Status'],'Approved for Client');assert.equal(fsheet[0]['Approved Version'],'1');assert.equal(fsheet[0].Observation,JSON.parse(oldFinding).Observation);assert.equal(rsheet[0]['Review Status'],'Reviewed');assert.equal(rsheet[0]['Review Operation Key'],JSON.parse(oldRec)['Review Operation Key']);assert.equal(fsheet[2]['Finding State'],'Draft');assert.equal(fsheet[2]['Expected Condition'],approved.expectedCondition);assert.equal(fsheet[2]['Supersedes Finding ID'],FINDING);assert.equal(rsheet[2]['Review Status'],'Draft');assert.equal(rsheet[2]['Supersedes Recommendation ID'],REC);assert.equal(h.records[h.c.FQ_FINDING_SETS_SHEET].sheet.records[0]['Finding IDs'],'FND-CORRECTION-1');assert.equal(JSON.stringify(fsheet[1]),synthF);assert.equal(JSON.stringify(rsheet[1]),synthR);assert.equal(h.records[h.c.FQ_ACTIONS_SHEET].sheet.records.length,0);});
test('approved wording and deterministic IDs remain exact across retry',()=>{const h=harness();const first=h.c.createPreSnapshotCorrectionDraftLocked_(h.selected,approved,{});const before=JSON.stringify(h.records);const retry=h.c.createPreSnapshotCorrectionDraftLocked_(h.selected,approved,{});assert.equal(first.findingId,retry.findingId);assert.equal(first.recommendationId,retry.recommendationId);assert.equal(retry.status,'already-completed');assert.equal(JSON.stringify(h.records),before);});
test('reviewed, snapshotted, or downstream Action authority fails closed',()=>{[{reviewedSet:true},{snapshot:true},{action:true}].forEach(o=>{const h=harness(o),before=JSON.stringify(h.records);assert.throws(()=>h.c.createPreSnapshotCorrectionDraftLocked_(h.selected,approved,{}));assert.equal(JSON.stringify(h.records),before);});});
test('missing or altered authority fails closed',()=>{const h=harness();h.c.assertRecommendationSeedIdentity_=()=>{throw new Error('changed');};const before=JSON.stringify(h.records);assert.throws(()=>h.c.createPreSnapshotCorrectionDraftLocked_(h.selected,approved,{}),/changed/);assert.equal(JSON.stringify(h.records),before);const m=harness();assert.throws(()=>m.c.createPreSnapshotCorrectionDraftLocked_(m.selected,Object.assign({},approved,{completionTest:''}),{}),/requires/);});

test('real approved-record lifecycle metadata does not invalidate the frozen Recommendation seed identity',()=>{
  const crypto=require('node:crypto');
  const c=vm.createContext({Object,Array,Date,JSON,Math,Number,String,RegExp,Set,isFinite,console,Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_algorithm,text)=>Array.from(crypto.createHash('sha256').update(String(text),'utf8').digest()).map(value=>value>127?value-256:value)}});
  ['FindingQualityEngine.gs','RecommendationDraftEngine.gs','FindingApprovalEngine.gs'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(ROOT,file),'utf8'),c,{filename:file}));
  c.reviewedPresenceEvidenceProjection_=record=>record;
  c.findingDraftEvidenceAuthorityProjection_=record=>record;
  const finding=Object.assign({},harness().finding,{'Finding State':'In Review','Approval Status':'In Review','Approved Version':'','Approval Operation Key':''});
  const authority={context:{'Prospect ID':PROSPECT,Version:'1'},presence:{'Prospect ID':PROSPECT,'Inventory Version':'1'},evidence:[{'Evidence ID':'EVID-1'},{'Evidence ID':'EVID-2'}],set:harness().set};
  const candidate=c.normalizeRecommendationDraftCandidate_({title:'Connect the Business Snapshot form to secure direct submission',recommendedAction:'Connect the Business Snapshot form to a secure submission system so customers can submit directly from the website.',implementationLocation:'Business Snapshot form submission workflow',intendedOutcome:'Create a simpler and more dependable lead-capture path with structured intake records and auditable follow-up.',dependencies:'',limitations:'Do not promise increased revenue, conversion rates, lead volume, or guaranteed results. Implementation and end-to-end submission testing have not yet occurred.'});
  const seed=c.buildRecommendationDraftOperationIdentity_(finding,authority,candidate);
  const recommendation={'Recommendation ID':seed.recommendationId,'Prospect ID':PROSPECT,'Finding Set ID':SET,'Finding Set Version':'1','Finding ID':FINDING,Title:candidate.title,'Recommended Action':candidate.recommendedAction,'Implementation Location':candidate.implementationLocation,'Intended Outcome':candidate.intendedOutcome,Dependencies:'','Review Status':'Reviewed','Operation Key':seed.operationKey,Limitations:candidate.limitations,'Reviewed By':'brian','Reviewed At':'2026-08-17','Review Operation Key':'FQRECOMMENDATIONREVIEW:key'};
  finding['Recommendation ID']=seed.recommendationId;
  finding['Approval Operation Key']=c.buildFindingApprovalOperationKey_(finding,recommendation,authority);
  finding['Finding State']='Actionable';finding['Approval Status']='Approved for Client';finding['Approved Version']='1';finding['Reviewed By']='approver';finding['Reviewed At']='2026-08-17T16:00:00Z';
  const schema={};
  assert.doesNotThrow(()=>c.assertRecommendationSeedIdentity_(schema,finding,recommendation,authority,candidate));
  assert.doesNotThrow(()=>c.assertRecommendationSeedIdentity_(schema,Object.assign({},finding,{'Superseded By Finding ID':'','Superseded By':'','Superseded At':'','Supersession Operation Key':'','Supersedes Finding ID':''}),Object.assign({},recommendation,{'Superseded By Recommendation ID':'','Supersedes Recommendation ID':''}),authority,candidate));
  assert.throws(()=>c.assertRecommendationSeedIdentity_(schema,finding,Object.assign({},recommendation,{'Recommended Action':recommendation['Recommended Action']+' Changed.'}),authority,c.normalizeRecommendationDraftCandidate_(Object.assign({},candidate,{recommendedAction:candidate.recommendedAction+' Changed.'}))),/content changed/);
  assert.throws(()=>c.assertRecommendationSeedIdentity_(schema,Object.assign({},finding,{Observation:finding.Observation+' Changed.'}),recommendation,authority,candidate),/Approved Finding content or authority changed/);
});
test('partial failure rolls back operation-owned rows and original membership',()=>{const h=harness(),findingBefore=h.c.FQ_FINDING_COLUMNS.map(x=>String(h.records[h.c.FQ_FINDINGS_SHEET].sheet.records[0][x]||'')),recBefore=h.c.FQ_RECOMMENDATION_COLUMNS.map(x=>String(h.records[h.c.FQ_RECOMMENDATIONS_SHEET].sheet.records[0][x]||'')),setBefore=h.c.FQ_FINDING_SET_COLUMNS.map(x=>String(h.records[h.c.FQ_FINDING_SETS_SHEET].sheet.records[0][x]||''));assert.throws(()=>h.c.createPreSnapshotCorrectionDraftLocked_(h.selected,approved,{afterFindingSet(){throw new Error('injected');}}),/injected/);assert.deepEqual(h.c.FQ_FINDING_COLUMNS.map(x=>String(h.records[h.c.FQ_FINDINGS_SHEET].sheet.records[0][x]||'')),findingBefore);assert.deepEqual(h.c.FQ_RECOMMENDATION_COLUMNS.map(x=>String(h.records[h.c.FQ_RECOMMENDATIONS_SHEET].sheet.records[0][x]||'')),recBefore);assert.deepEqual(h.c.FQ_FINDING_SET_COLUMNS.map(x=>String(h.records[h.c.FQ_FINDING_SETS_SHEET].sheet.records[0][x]||'')),setBefore);assert.equal(h.records[h.c.FQ_FINDINGS_SHEET].sheet.records.length,2);assert.equal(h.records[h.c.FQ_RECOMMENDATIONS_SHEET].sheet.records.length,2);});

function capacitySheet(initialColumns,maxRows=6){let maxColumns=initialColumns;const cells=Array.from({length:maxRows},()=>Array(initialColumns).fill(''));return{cells,getMaxRows:()=>maxRows,getMaxColumns:()=>maxColumns,insertColumnsAfter(after,count){assert.equal(after,maxColumns);for(const row of cells)row.push(...Array(count).fill(''));maxColumns+=count;},deleteColumns(start,count){for(const row of cells)row.splice(start-1,count);maxColumns-=count;},getRange(row,column,rowCount=1,columnCount=1){if(column+columnCount-1>maxColumns)throw new Error('outside dimensions');const slice=()=>Array.from({length:rowCount},(_,r)=>Array.from({length:columnCount},(_,c)=>cells[row-1+r][column-1+c]));return{getValues:slice,getDisplayValues:slice,getDisplayValue:()=>String(cells[row-1][column-1]||''),setValues(values){values.forEach((valuesRow,r)=>valuesRow.forEach((value,c)=>{cells[row-1+r][column-1+c]=value;}));},clearContent(){for(let r=0;r<rowCount;r++)for(let c=0;c<columnCount;c++)cells[row-1+r][column-1+c]='';},getDataValidations:()=>Array.from({length:rowCount},()=>Array(columnCount).fill(null)),setDataValidations(){}};},getColumnWidth:()=>100,setColumnWidth(){},isColumnHiddenByUser:()=>false,hideColumns(){},showColumns(){}};}

test('capacity expansion allocates only missing physical columns and is idempotent',()=>{const h=harness(),findings=capacitySheet(33),recommendations=capacitySheet(18);const schema={};schema[h.c.FQ_FINDINGS_SHEET]={sheet:findings,requiredLastColumn:38};schema[h.c.FQ_RECOMMENDATIONS_SHEET]={sheet:recommendations,requiredLastColumn:18};const snapshots={dimensions:{}};snapshots.dimensions[h.c.FQ_FINDINGS_SHEET]={maxRows:6,maxColumns:33,addedColumns:0};snapshots.dimensions[h.c.FQ_RECOMMENDATIONS_SHEET]={maxRows:6,maxColumns:18,addedColumns:0};h.c.ensurePreSnapshotSheetCapacity_(schema,snapshots);assert.equal(findings.getMaxColumns(),38);assert.equal(recommendations.getMaxColumns(),18);assert.equal(snapshots.dimensions[h.c.FQ_FINDINGS_SHEET].addedColumns,5);h.c.ensurePreSnapshotSheetCapacity_(schema,snapshots);assert.equal(findings.getMaxColumns(),38);});

test('safe rollback restores original dimensions after expansion or installed headers',()=>{const h=harness(),findings=capacitySheet(33),recommendations=capacitySheet(16);const schema={};schema[h.c.FQ_FINDINGS_SHEET]={sheet:findings,requiredLastColumn:38,missingHeaders:['A','B','C','D','E'],table:{headers:{A:34,B:35,C:36,D:37,E:38}}};schema[h.c.FQ_RECOMMENDATIONS_SHEET]={sheet:recommendations,requiredLastColumn:18,missingHeaders:['R1','R2'],table:{headers:{R1:17,R2:18}}};const snapshots={dimensions:{},columnContracts:{}};[h.c.FQ_FINDINGS_SHEET,h.c.FQ_RECOMMENDATIONS_SHEET].forEach(name=>{snapshots.dimensions[name]={maxRows:6,maxColumns:schema[name].sheet.getMaxColumns(),addedColumns:0};snapshots.columnContracts[name]=[];});h.c.ensurePreSnapshotSheetCapacity_(schema,snapshots);findings.cells[0].splice(33,5,'A','B','C','D','E');recommendations.cells[0].splice(16,2,'R1','R2');assert.equal(h.c.rollbackPreSnapshotCapacity_(schema,snapshots).length,0);assert.equal(findings.getMaxColumns(),33);assert.equal(recommendations.getMaxColumns(),16);});

test('ambiguous rollback preserves allocated columns and clears only operation-owned headers',()=>{const h=harness(),findings=capacitySheet(33),recommendations=capacitySheet(18);const schema={};schema[h.c.FQ_FINDINGS_SHEET]={sheet:findings,requiredLastColumn:38,missingHeaders:['A','B','C','D','E'],table:{headers:{A:34,B:35,C:36,D:37,E:38}}};schema[h.c.FQ_RECOMMENDATIONS_SHEET]={sheet:recommendations,requiredLastColumn:18,missingHeaders:[],table:{headers:{}}};const snapshots={dimensions:{},columnContracts:{}};snapshots.dimensions[h.c.FQ_FINDINGS_SHEET]={maxRows:6,maxColumns:33,addedColumns:0};snapshots.dimensions[h.c.FQ_RECOMMENDATIONS_SHEET]={maxRows:6,maxColumns:18,addedColumns:0};snapshots.columnContracts[h.c.FQ_FINDINGS_SHEET]=[];snapshots.columnContracts[h.c.FQ_RECOMMENDATIONS_SHEET]=[];h.c.ensurePreSnapshotSheetCapacity_(schema,snapshots);findings.cells[0][33]='A';findings.cells[2][34]='unowned';const limitations=h.c.rollbackPreSnapshotCapacity_(schema,snapshots);assert.equal(findings.getMaxColumns(),38);assert.equal(findings.cells[0][33],'');assert.equal(findings.cells[2][34],'unowned');assert.match(limitations[0],/unowned data/);});

test('schema capacity source supports hidden or reordered headers and independent affected sheets',()=>{const source=fs.readFileSync(path.join(ROOT,'PreSnapshotRecoveryEngine.gs'),'utf8');assert.match(source,/getMaxColumns\(\)/);assert.match(source,/insertColumnsAfter\(current,needed\)/);assert.match(source,/FQ_FINDINGS_SHEET,FQ_RECOMMENDATIONS_SHEET/);assert.match(source,/afterCapacityExpansion/);assert.match(source,/afterHeaderInstallation/);assert.doesNotMatch(source,/insertColumnsAfter\(33|deleteColumns\(34/);});
test('source installs explicit lifecycle/linkage and future approval validates before write',()=>{const source=fs.readFileSync(path.join(ROOT,'PreSnapshotRecoveryEngine.gs'),'utf8'),fq=fs.readFileSync(path.join(ROOT,'FindingQualityEngine.gs'),'utf8'),approval=fs.readFileSync(path.join(ROOT,'FindingApprovalEngine.gs'),'utf8'),menu=fs.readFileSync(path.join(ROOT,'Menu.gs'),'utf8');assert.match(menu,/Create Pre-Snapshot Correction Draft/);assert.match(fq,/Superseded Pre-Snapshot/);assert.match(source,/Superseded By Finding ID/);assert.match(source,/Supersedes Recommendation ID/);assert.match(source,/migratePreSnapshotSchema_/);assert.match(source,/rollbackPreSnapshotRecovery_/);assert.match(approval,/validateAssessmentFindingRecord_\(finding/);assert.ok(approval.indexOf('validateAssessmentFindingRecord_(finding')<approval.indexOf('writeFindingQualityRecord_('));assert.doesNotMatch(source,/generateExecutive|buildApprovedFindingSetSnapshot_|Gmail|UrlFetch|Pdf|Preview|1aoOL0|FQ-2/i);});
