const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..'),fq=fs.readFileSync(path.join(ROOT,'FindingQualityEngine.gs'),'utf8'),stage1=fs.readFileSync(path.join(ROOT,'FindingSetCorrectionEngine.gs'),'utf8'),stage2=fs.readFileSync(path.join(ROOT,'PreSnapshotRecoveryEngine.gs'),'utf8'),menu=fs.readFileSync(path.join(ROOT,'Menu.gs'),'utf8');
const corrected={
 'Finding Title':'Business Snapshot intake adds an email handoff',
 Observation:'The Business Snapshot form is not connected to a secure submission endpoint. It prepares an email for the visitor to review and send.',
 'Expected Condition':'Visitors submit the Business Snapshot directly on the website and receive confirmation without opening or sending an email.',
 'Business Consequence':'The extra step can cause abandoned or incomplete requests. It also makes lead tracking less dependable.',
 'Consequence Basis':'The page states that its secure submission endpoint is not connected. The form instead prepares an email that the visitor must send. This added handoff prevents the website from recording a completed structured submission directly.',
 'Recommended Action':'Connect the Business Snapshot form to a secure submission system so customers can submit directly from the website. Each valid submission should create the appropriate linked intake records and preserve explicit consent. Rogers Holdings should receive a notification, and the visitor should receive clear confirmation. No manually sent email should be required.',
 'Implementation Location':'Business Snapshot form submission workflow',
 'Intended Outcome':'Create a simpler and more dependable lead-capture path with structured intake records and auditable follow-up.',
 'Completion Test':'Submit an authorized test Business Snapshot through the published form. Verify that no email client is required. Confirm one complete linked intake record contains the submitted fields and consent. Confirm Rogers Holdings receives the configured notification. Confirm the visitor receives a clear confirmation. Verify invalid submissions create no incomplete records.'
};
function load(){const c=vm.createContext({Object,Array,Date,JSON,Math,Number,String,RegExp,Set,isFinite});vm.runInContext(fq,c);return c;}
test('all required client-facing Finding sentences pass the shared 18-word tokenizer',()=>{const c=load();assert.deepEqual(Array.from(c.validatePlainLanguageFindingFields_(corrected)),[]);for(const [field,value] of Object.entries(corrected))for(const sentence of value.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean))assert.ok(sentence.split(/\s+/).length<=18,field+': '+sentence);});
test('overlength correction fails before either approval boundary',()=>{const c=load(),bad=Object.assign({},corrected,{'Business Consequence':corrected['Business Consequence']+' This added sentence contains far too many words for the approved client-facing plain-language contract and must fail closed immediately.'});assert.ok(c.validatePlainLanguageFindingFields_(bad).some(x=>/LONG_SENTENCE_BUSINESSCONSEQUENCE/.test(x)));assert.match(stage2,/validatePlainLanguageFindingFields_\(staged\.finding\)/);assert.match(fq,/transitionSelectedFindingSet_[\s\S]*assertPlainLanguageFindingSetForApproval_/);});
test('Stage 1 is confirmed, audited, locked, capacity-safe, retryable, and rollback-scoped',()=>{assert.match(menu,/Return Selected Finding Set to Draft for Correction/);assert.match(stage1,/RETURN FINDING SET TO DRAFT/);assert.match(stage1,/getDocumentLock/);assert.match(stage1,/insertColumnsAfter/);assert.match(stage1,/Previous Review Submitted By/);assert.match(stage1,/Return Operation Key/);assert.match(stage1,/already-completed/);assert.match(stage1,/deleteColumns/);assert.doesNotMatch(stage1,/generateExecutive|Pdf|Gmail|Activity|UrlFetch|1aoOL0|FQ-2/);});
test('Stage 2 requires audited return and creates second-generation reciprocal Draft successors',()=>{assert.match(stage2,/A manually returned Draft Finding Set is not correction authority/);assert.match(stage2,/assertReturnedFindingSet_/);assert.match(stage2,/businessConsequence/);assert.match(stage2,/recommendedAction/);assert.match(stage2,/Supersedes Finding ID/);assert.match(stage2,/Supersedes Recommendation ID/);assert.match(stage2,/Superseded By Finding ID/);assert.match(stage2,/Superseded By Recommendation ID/);});
test('approval and review boundaries share the same validator',()=>{const approval=fs.readFileSync(path.join(ROOT,'FindingApprovalEngine.gs'),'utf8');assert.match(approval,/validatePlainLanguageFindingFields_\(finding\)/);assert.match(fq,/assertPlainLanguageFindingSetForApproval_\(loadFindingQualityApprovalBundle_/);assert.match(fq,/assertPlainLanguageFindingSetForApproval_\(bundle\)/);});
